type User {
    name: String!
    email: String!
    posts: [Post] @hasMany(as: "author")
    likes: [Like] @hasMany(as: "author")
    comments: [Comment] @hasMany(as: "author")
    files: [File] @belongsToMany(as: "author")
}